name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install ARM GCC
        run: sudo apt-get update && sudo apt-get install -y gcc-arm-none-eabi

      - name: Build
        run: |
          # Переходимо в папку з проектом P2P
          cd projects/ASR6601CB-EVAL/examples/lora_p2p
          # Запускаємо збірку
          make
          
      - name: Upload firmware
        uses: actions/upload-artifact@v3
        with:
          name: p2p-firmware
          path: projects/ASR6601CB-EVAL/examples/lora_p2p/*.bin
